name = "reddit_client"
version = "0.1.0"
description = "Reddit Clone CLI Client in Gleam"
target = "erlang"

[dependencies]
gleam_stdlib = "0.65.0"
gleam_erlang = "1.3.0"
argv = "1.0.2"

[erlang]
extra_applications = ["inets"]

[dev-dependencies]
gleeunit = "1.6.1"
