name = "simulator"
version = "0.1.0"
description = "Load generator simulator"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_otp = ">= 0.10.0 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 2.0.0"
argv = ">= 1.0.0 and < 2.0.0"
engine = { path = "../engine" }

[dev-dependencies]
gleeunit = "~> 1.0"


