name = "engine"
version = "0.1.0"
description = "Reddit-like engine (actors + SQLite)"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_otp = ">= 0.10.0 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 2.0.0"
sqlight = ">= 1.0.3 and < 2.0.0"
wisp = ">= 2.0.0 and < 3.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_http = ">= 3.5.0 and < 5.0.0"
mist = ">= 2.0.0 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
