name = "engine"
version = "0.1.0"
description = "Reddit-like engine (actors + SQLite)"
target = "erlang"

[dependencies]
gleam_stdlib = "0.65.0"
gleam_otp = "1.2.0"
gleam_erlang = "1.3.0"
sqlight = "1.0.3"

[erlang]
extra_applications = ["inets"]

[dev-dependencies]
gleeunit = "1.6.1"
